set FOREIGN_KEY_CHECKS=0;
truncate table `academicInstitution`;
truncate table `administrator`;
truncate table `appeal`;
truncate table `expert`;
truncate table `follow`;
truncate table `keyword`;
truncate table `message`;
truncate table `notice`;
truncate table `order`;
truncate table `paper`;
truncate table `patent`;
truncate table `project`;
truncate table `report`;
truncate table `resource`;
truncate table `user`;
set FOREIGN_KEY_CHECKS=1;